import Navbar from "@/components/Navbar";
import { Provider } from "@/components/ui/provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
          <nav>
            <Navbar />
          </nav>

          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
