import { Provider } from "@/components/ui/provider";
import type { Metadata } from "next";

//fonts
import { DM_Sans } from "next/font/google";
import { DM_Serif_Display } from "next/font/google";

const dmSerifDisplay = DM_Serif_Display({ subsets: ["latin"], weight: "400" });
const dmSans = DM_Sans({ subsets: ["latin"] });

//components
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html suppressHydrationWarning>
      <body className={dmSans.className}>
        <Provider>
          <nav>
            <Navbar />
          </nav>

          <main>{children}</main>

          <footer>
            <Footer />
          </footer>
        </Provider>
      </body>
    </html>
  );
}
